#!/bin/bash

# Path to colors.json generated by Pywal
# Using ${XDG_CACHE_HOME:-$HOME/.cache} is slightly more robust
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
COLOR_FILE="$CACHE_DIR/wal/colors.json"

# --- Sanity Checks ---

# 1. Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Error: jq is not installed. Please install it to parse JSON." >&2
    exit 1
fi

# 2. Check if colors.json exists
if [ ! -f "$COLOR_FILE" ]; then
    echo "Error: colors.json not found at $COLOR_FILE" >&2
    echo "Ensure Pywal has run successfully." >&2
    exit 1
fi

# --- Extract Colors ---
# Access colors within the "colors" object using .colors.colorX
# Use || echo "fallback_color" to provide a default if a key is missing,
# or add checks after extraction. Using black/white as simple fallbacks here.
color0=$(jq -r '.colors.color0 // "#000000"' "$COLOR_FILE")
color1=$(jq -r '.colors.color1 // "#FF0000"' "$COLOR_FILE") # Red fallback
color2=$(jq -r '.colors.color2 // "#00FF00"' "$COLOR_FILE") # Green fallback
color3=$(jq -r '.colors.color3 // "#FFFF00"' "$COLOR_FILE") # Yellow fallback
color4=$(jq -r '.colors.color4 // "#0000FF"' "$COLOR_FILE") # Blue fallback
color5=$(jq -r '.colors.color5 // "#FF00FF"' "$COLOR_FILE") # Magenta fallback
color6=$(jq -r '.colors.color6 // "#00FFFF"' "$COLOR_FILE") # Cyan fallback
color7=$(jq -r '.colors.color7 // "#FFFFFF"' "$COLOR_FILE") # White fallback

# --- Debugging ---
# Optional: Uncomment to verify extracted colors before writing the CSS
# echo "Extracted colors:"
# echo "color0: $color0"
# echo "color1: $color1"
# echo "color2: $color2"
# echo "color3: $color3"
# echo "color4: $color4"
# echo "color5: $color5"
# echo "color6: $color6"
# echo "color7: $color7"

# --- Check for Extraction Errors ---
# A simple check: if color0 is still the fallback or empty/null, something went wrong.
if [[ -z "$color0" || "$color0" == "null" || "$color0" == "#000000" ]]; then
     # Check if color0 was actually black in the file
     actual_color0=$(jq -r '.colors.color0' "$COLOR_FILE")
     if [[ "$actual_color0" != "#000000" && "$actual_color0" != *"000000"* ]]; then # Allow for #000 variants
        echo "Warning: Failed to extract colors correctly from $COLOR_FILE." >&2
        echo "Please check the file structure and jq paths (e.g., .colors.color0)." >&2
        # Decide whether to exit or proceed with potentially wrong colors
        # exit 1 # Uncomment to exit if colors are likely wrong
     fi
fi


# --- Create Waybar CSS ---
# Ensure the target directory exists
WAYBAR_CONFIG_DIR="$HOME/.config/waybar"
mkdir -p "$WAYBAR_CONFIG_DIR"

# Use printf for potentially safer variable expansion, though cat EOF is usually fine.
printf "/* Waybar Theme from Pywal */\n\n" > "$WAYBAR_CONFIG_DIR/style.css"
printf "#waybar {\n    background: %s;\n    color: %s;\n}\n\n" "$color0" "$color7" >> "$WAYBAR_CONFIG_DIR/style.css"
printf "#clock {\n    color: %s;\n}\n\n" "$color6" >> "$WAYBAR_CONFIG_DIR/style.css"
printf "#cpu {\n    color: %s;\n}\n\n" "$color4" >> "$WAYBAR_CONFIG_DIR/style.css"
printf "#network {\n    color: %s;\n}\n\n" "$color2" >> "$WAYBAR_CONFIG_DIR/style.css"
printf "#memory {\n    color: %s;\n}\n\n" "$color5" >> "$WAYBAR_CONFIG_DIR/style.css"
# Add more elements and styling as needed
# Example:
# printf "#custom-weather {\n    color: %s;\n}\n\n" "$color3" >> "$WAYBAR_CONFIG_DIR/style.css"

echo "Waybar style.css generated at $WAYBAR_CONFIG_DIR/style.css"
echo "Reload Waybar for changes to take effect (e.g., killall -SIGUSR2 waybar)"

