-- ~/.config/wal/templates/colors.lua.tpl
-- Pywal Colors (Generated on {{timestamp}})
-- This file is automatically generated from your Pywal cache. Do not edit manually.

return {
    -- Alpha value (e.g., for transparency - adjust if needed)
    -- You could potentially extract this from wal's cache too if you use 'wal -a'
    alpha = "100", -- Defaulting to opaque

    -- Special colors based on ~/.cache/wal/colors.json mapping
    special = {
        background = "{{background}}", -- Wallpaper background color
        foreground = "{{foreground}}", -- Text foreground color
        cursor = "{{cursor}}"      -- Cursor color (often same as foreground)
    },

    -- ANSI colors (0-15)
    colors = {
        -- Regular Colors (0-7)
        color0 = "{{color0}}",  -- Black
        color1 = "{{color1}}",  -- Red
        color2 = "{{color2}}",  -- Green
        color3 = "{{color3}}",  -- Yellow
        color4 = "{{color4}}",  -- Blue
        color5 = "{{color5}}",  -- Magenta
        color6 = "{{color6}}",  -- Cyan
        color7 = "{{color7}}",  -- White

        -- Bright Colors (8-15)
        color8 = "{{color8}}",  -- Bright Black (Gray)
        color9 = "{{color9}}",  -- Bright Red
        color10 = "{{color10}}", -- Bright Green
        color11 = "{{color11}}", -- Bright Yellow
        color12 = "{{color12}}", -- Bright Blue
        color13 = "{{color13}}", -- Bright Magenta
        color14 = "{{color14}}", -- Bright Cyan
        color15 = "{{color15}}"  -- Bright White (often same as foreground)
    }
}
